name: Release to Production

on:
  push:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker:
    name: "Release Docker image"
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.go.outputs.version }}
    steps:
      - id: Checkout Repository
        uses: actions/checkout@v3

      - id: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: determine version
        run: |
          npm install @semantic-release/exec -D
          npm install @semantic-release/changelog -D
          npm install @semantic-release/git -D
          npx semantic-release --dry-run
          cat VERSION.env
          source VERSION.env
          echo "::set-output name=version::$VERSION"

      - name: Set up QEMU
        if: ${{ steps.dependencies.outputs.VERSION != ''}}
        uses: docker/setup-qemu-action@v2

      -  name: Set up Docker Buildx
        if: ${{ steps.dependencies.outputs.VERSION != ''}}
        uses: docker/setup-buildx-action@v2


      - name: Login to GHCR
        if: ${{ steps.dependencies.outputs.VERSION != ''}}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push
        if: ${{ steps.dependencies.outputs.VERSION != ''}}
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: VERSION=${{steps.dependencies.outputs.VERSION}}
          platforms: linux/amd64,linux/arm64
          push: true
            tags: ghcr.io/${{ github.repository }}:${{steps.dependencies.outputs.VERSION}}

            
      - name: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              npm install @semantic-release/exec -D
              npm install @semantic-release/changelog -D
              npm install @semantic-release/github -D
              npm install @semantic-release/git -D
              npx semantic-release
